### PR TITLE
Merge Zhangyuanwei/master

### PR DESCRIPTION
**Pull request by JameelJiwani**

### CODE REVIEW

**Comment by JameelJiwani** [comment]
I think vendor/darwin-x64-binding.node should be excluded or rebuilt. It might have some garbage in it from merging the two branches.

I'm curious to know why these are being committed and not generated at runtime 🤔

**Comment by paulxuca** [comment]
These files can't be generated at runtime since they're compiled C binaries. Furthermore, to compile a binary for different architectures requires the build machine to be based on that arch. For now I'd suggest using the original non-forked version of the package to develop locally until I can confirm the updated binaries can be used. We've made some modifications to the package in order to support our custom use case.

**Comment by JameelJiwani** [comment]
> These files can't be generated at runtime since they're compiled C binaries. Furthermore, to compile a binary for different architectures requires the build machine to be based on that arch. For now I'd suggest using the original non-forked version of the package to develop locally until I can confirm the updated binaries can be used. We've made some modifications to the package in order to support our custom use case.

It's a non-blocker at the moment but it would be nice if we could get this package up-to-date so it can support newer architectures. For now, I can use the original package but I will be unable to render avatars until we sort this issue out.

If there are any obvious mistakes in this package other than the binaries, let me know and I can do my best to to get this branch into a working state.

**Comment by JameelJiwani** [comment]
Can we merge this?

**Pull request closed without merging**
